mackerelio/mackerel-client-ruby

- lib/mackerel/client.rb
Caching `http_client` instance would save some time and resources when making multiple requests in a row.
> Memoize `http_client` to improve performance

- lib/mackerel/client.rb
`/api/v0/hosts.json` accepts `status` parameters, but mackerel-client-ruby's `get_hosts` doesn't accept them.
So I added a new key `status` to `req.params`.
> Make get_hosts accepts status option

- lib/mackerel-client.rb
bundler invoke `require GEMNAME` with `Bundler.setup`. I added simple helper file for bundler specification. many of gems  adopted this workaround like this:
* https://github.com/kpumuk/meta-tags/blob/master/lib/meta-tags.rb
* https://github.com/r7kamura/rspec-json_matcher/blob/master/lib/rspec-json_matcher.rb
* etc...etc...
How do you think about this helper file? I think this helper is useful under the bundler environment.
> Added helper file for auto require specification of bundler

- .travis.yml
- lib/mackerel/client.rb
- spec/mackerel/client_spec.rb
Mackerel provides an API to create a graph definition, but Mackerel::Client does not supported yet.
(Also updated Bundler to fix build)
> Add #define_graphs method to Mackerel::Client

- lib/mackerel/client/helper.rb
- spec/mackerel/client/helper_spec.rb
Mackerel's metric name has some constraint:
http://help.mackerel.io/entry/spec/api/v0#graphdef-post
> which may contain [-a-zA-Z0-9_]+ , and wildcard characters * , or #
http://help-ja.mackerel.io/entry/spec/api/v0#graphdef-post
> [-a-zA-Z0-9_]+またはワイルドカード*, #
If we create a definition of graphs, we may write some code like:
https://github.com/aereal/psi-metrics/blob/master/Rakefile#L36-L38
> Add Mackerel::Client::Helper.as_safe_metric_name

- lib/mackerel/client.rb
- spec/mackerel/client_spec.rb
I'd like to add devices on which we cannot install mackerel-agent.
For example, [nasne](http://www.jp.playstation.com/nasne/), [Netatmo Weather Station](https://www.netatmo.com/ja-JP/product/weather-station) and so on.
So I've added the feature to support `POST /api/v1/hosts`.
Please check it.
Thanks in advance.
> Support POST /api/v0/hosts

- .travis.yml
- lib/mackerel/client.rb
Hi. I encountered this situation that td-agent is no response.
"no response" means td-agent is not stopped, but not output logs.
EXPLAIN: sigdump
```
Sigdump at 2016-07-01 12:58:59 +0900 process 7846 (/usr/sbin/td-agent)
Thread #<Thread:0x007f04ae59e660> status=run priority=0
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.3/lib/sigdump.rb:39:in `backtrace'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.3/lib/sigdump.rb:39:in `dump_backtrace'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.3/lib/sigdump.rb:25:in `block in dump_all_thread_backtrace'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.3/lib/sigdump.rb:24:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/sigdump-0.2.3/lib/sigdump.rb:24:in `dump_all_thread_backtrace' …
```
> ADD timeout, open_timeout setting to Mackerel API Request + FIX Travis CI on Ruby environment 1.9.3 + ADD Travis CI on Ruby environment 2.2

- lib/mackerel/client.rb
Hi,
I found a typo when I called `define_graphs` method. 
If you check and it is all right, could you merge?
Thank you.
> Typo for `response`

- lib/mackerel/client.rb
- spec/mackerel/client_spec.rb
ref(ja): https://mackerel.io/ja/api-docs/entry/graph-annotations
Implemented only `POST /api/v0/graph-annotations`, to create graph annotations in Capistrano deploy hook.
> Support posting graph annotations

- spec/mackerel/client_spec.rb
A request parameter in test spec added in #28 is wrong, so fix it.
(Though this change itself doesn't affect mackerel-client-ruby's behavior, but wrong parameters may confuse users.)
> [nit] Fix a request parameter in test.

- lib/mackerel/client.rb
- spec/mackerel/client_spec.rb
This PR adds following methods to `Mackerel::Client`.
- `list_metadata(host_id)`
- `get_metadata(host_id, namespace)`
- `update_metadata(host_id, namespace)`
- `delete_metadata(host_id, namespace)`
I think we need to refactor test code... 😃
> Add support for metadata APIs

- README.md
- lib/mackerel.rb
- lib/mackerel/client.rb
- lib/mackerel/version.rb
`require 'mackerel/client'` has been enough declaration to use `Mackerel::Client` in client < 0.4.0, but it does not work with 0.4.0. (ref: https://github.com/mackerelio/fluent-plugin-mackerel/pull/28)
Though it's not documented in this repository, requiring only 'mackerel/client' is described in many pages, even in our help: https://mackerel.io/docs/entry/advanced/capistrano-2.x
So, I'd like to restore the behavior.
> Make Mackerel::Client works with `require 'mackerel/client'`

- .rspec
- mackerel-client.gemspec
- spec/mackerel/alert_spec.rb
- spec/mackerel/annotation_spec.rb
- spec/mackerel/channel_spec.rb
- spec/mackerel/client/helper_spec.rb
- spec/mackerel/client_spec.rb
- spec/mackerel/dashboard_spec.rb
- spec/mackerel/invitation_spec.rb
- spec/mackerel/metric_spec.rb
- spec/mackerel/monitor_spec.rb
- spec/mackerel/monitoring_spec.rb
- spec/mackerel/notification_group_spec.rb
- spec/mackerel/organization_spec.rb
- spec/mackerel/service_spec.rb
- spec/mackerel/user_spec.rb
- spec/spec_helper.rb
* Relax development gem requirements
* RSpec can upgrade to v3.x if there are no warnings on v2.99
* Configure spec_helper, .rspec
* Add configurations that are well configured
> Use Rspec v3.x

- lib/mackerel/api_command.rb
here are some examples.
- initialize 'Authorization' header set when generating a client object by mistake
- initialize 'User-Agent' header ('Faraday v0.15.2') by mistake
merge http headers to avoid to initialize http headers that a faraday client object has
> fix unintended initializing http headers

- lib/mackerel/api_command.rb
- lib/mackerel/client.rb
- lib/mackerel/error.rb
- spec/mackerel/alert_spec.rb
- spec/mackerel/annotation_spec.rb
- spec/mackerel/api_commend_spec.rb
- spec/mackerel/channel_spec.rb
- spec/mackerel/client_spec.rb
- spec/mackerel/dashboard_spec.rb
- spec/mackerel/invitation_spec.rb
- spec/mackerel/metric_spec.rb
- spec/mackerel/monitor_spec.rb
- spec/mackerel/monitoring_spec.rb
- spec/mackerel/notification_group_spec.rb
- spec/mackerel/organization_spec.rb
- spec/mackerel/service_spec.rb
- spec/mackerel/user_spec.rb
To raise error when mackerel.io returns 401 Unauthorized
Since `Mackerel::ApiCommand#check_status` is very simple,
change it to use built-in `Faraday::Response::RaiseError` Middleware.
https://github.com/lostisland/faraday/blob/v0.15.4/lib/faraday/response/raise_error.rb
1. Change the error message to json["error"] from API.
2. All 4xx Client Error and 5xx Server Error will raise `Mackerel::Error` (`< StandardError`)
However, NoMethodError would have been raised in these following lines.
i.e. #get_services
https://github.com/mackerelio/mackerel-client-ruby/blob/v0.7.0/lib/mackerel/service.rb#L32-L33
```
data['services'].map {|s| Mackerel::Service.new(s) }
```
i.e. #get_host
https://github.com/mackerelio/mackerel-client-ruby/blob/v0.7.0/lib/mackerel/host.rb#L66-L67
``` …
```
> Use Faraday::Response::RaiseError middleware

- lib/mackerel/api_command.rb
- mackerel-client.gemspec
faraday v1.0.0 is shipped at 2020-01-01
https://rubygems.org/gems/faraday/versions/1.0.0
In faraday v1.0, `Faraday::Error::ClientError` has been split into `Faraday::ClientError` and `Faraday::SeverError`.
https://github.com/lostisland/faraday/blob/ff9dc1d121/lib/faraday/response/raise_error.rb#L9-L10
https://github.com/lostisland/faraday/blob/ff9dc1d121/lib/faraday/response/raise_error.rb#L31-L34
https://github.com/lostisland/faraday/blob/v0.17.3/lib/faraday/response/raise_error.rb#L3
https://github.com/lostisland/faraday/blob/v0.17.3/lib/faraday/response/raise_error.rb#L14-L15
* `Faraday::Error::Client` is deprecated (since v0.17.1)
- https://github.com/lostisland/faraday/commit/6e746fceefe0d1f75535b40a62d846a6a95bf85f
* `Faraday::Response::RaiseError` uses `Faraday::ClientError` …
> Use faraday v1.0

- .travis.yml
- Add 2.7
- Drop 2.3
- It has already reached EOL https://www.ruby-lang.org/en/downloads/branches/
> modify CI target ruby version

- lib/mackerel/client.rb
- lib/mackerel/downtime.rb
- spec/mackerel/downtime_spec.rb
I want to call `/api/v0/downtime` API using mackerel-client-ruby, but it seems not to implement yet.
https://mackerel.io/ja/api-docs/entry/downtimes#create
If these API are already implemented, or there is some reason why it doesn't implement , please tell me and close this PR. 
thanks.
> Implements downtime API

- lib/mackerel/monitor.rb
- spec/mackerel/monitor_spec.rb
I want to get a monitor by its id.
```ruby
client = Mackerel::Client.new(:mackerel_api_key => ENV['MACKEREL_APIKEY'])
m = client.get_monitor('********')
pp m
```
output
```sh
#<Mackerel::Monitor:*****
@certificationExpirationCritical=nil,
@certificationExpirationWarning=nil,
@containsString=nil,
@critical=***,
@duration=***,
@excludeScopes=[],
@expression=nil,
@id="*****",
@isMute=false,
@maxCheckAttempts=1,
@metric="******",
@name="******",
.....
```
> Add get monitor

- .github/workflows/ci.yml
I fixed `The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/` in https://github.com/mackerelio/mackerel-client-ruby/actions/runs/6806586943
> update version for checkout action

- mackerel-client.gemspec
I fixed this warning in gem build.
```
WARNING:  license value 'Apache 2' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
Did you mean 'Apache-2.0'?
```
> fix invalid license

- lib/mackerel/channel.rb
- spec/mackerel/channel_spec.rb
`suspendedAt` is added to Channels API.
https://mackerel.io/ja/api-docs/entry/channels#get
> Add suspendedAt to Channels API

- .github/workflows/ci.yml
Ruby 2.6 is EOL
Ruby 3.2 and 3.3 are available
https://www.ruby-lang.org/ja/downloads/branches/
> Drop 2.6 and add 3.2 and 3.3
